#!/bin/bash
#creator by RedRoot(Yaciyna Mikhail) for GAMER STATION [on linux] and Gaming Community OS Linux
# GPL-3.0 License 

# переменные
CLOUD_PATCH="/home/$USER/Yandex.Disk/NEW-CLOUD-SAVE-GAMES/minetest"


# функции



# команды удаление / архивации / копирования
rm -f "$CLOUD_PATCH/.minetest-backup.tar.xz" || echo "файл бикапа не существует"
cp -f "$CLOUD_PATCH/.minetest.tar.xz" "$CLOUD_PATCH/.minetest-backup.tar.xz"
cd "/home/$USER" 
tar -zcvf .minetest.tar.xz .minetest || echo "папки с игрой не существует!"
mv -f .minetest.tar.xz "$CLOUD_PATCH"
